--- #YAML:1.0
name:                Algorithm-AhoCorasick
version:             0.02
abstract:            efficient search for multiple strings
license:             ~
author:              
    - Vaclav Barta <vbar@comp.cz>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
